export const data = [
  { "id": 1, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 2, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 3, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 4, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 5, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 6, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 7, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 8, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 9, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 10, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 11, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 12, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 13, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 14, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 15, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 16, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 17, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 18, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 19, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 20, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 21, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 22, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 23, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 24, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 25, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 26, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 27, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 28, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 29, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 30, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },
  { "id": 31, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 32, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 33, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 34, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 35, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 36, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 37, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 38, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 39, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 40, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 41, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 42, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 43, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 44, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 45, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 46, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 47, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 48, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 49, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 50, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 51, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 52, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 53, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 54, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 55, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 56, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 57, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 58, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 59, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 60, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 61, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 62, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 63, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 64, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 65, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 66, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 67, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 68, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 69, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 70, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 71, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 72, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 73, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 74, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 75, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 76, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 77, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 78, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 79, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 80, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 81, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 82, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 83, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 84, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 85, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 86, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 87, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 88, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 89, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 90, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 91, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 92, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 93, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 94, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 95, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 96, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 97, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 98, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 99, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 100, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" }
];

export const ApiData = [
  {
    "id": 1,
    "name": "Emily Johnson",
    "company": "ABC Corporation",
    "username": "emily_johnson",
    "email": "emily.johnson@abccorporation.com",
    "address": "123 Main St",
    "zip": "12345",
    "state": "California",
    "country": "Italy",
    "phone": "+1-555-123-4567",
    "photo": "https://loremflickr.com/2131/1982?lock&#x3D;7002580341502095"
  },
  {
    "id": 2,
    "name": "Michael Williams",
    "company": "ABC Corporation",
    "username": "michael_williams",
    "email": "michael.williams@xyzcorp.com",
    "address": "456 Elm Ave",
    "zip": "67890",
    "state": "New York",
    "country": "USA",
    "phone": "+1-555-987-6543"
  },
  {
    "id": 3,
    "name": "John Smith",
    "company": "Acme Inc.",
    "username": "john_smith",
    "email": "john.smith@acmeinc.com",
    "address": "789 Oak Rd",
    "zip": "54321",
    "state": "Texas",
    "country": "USA",
    "phone": "+1-555-222-3333"
  },
  {
    "id": 4,
    "name": "Emma Davis",
    "company": "Tech Solutions Ltd.",
    "username": "emma_davis",
    "email": "emma.davis@techsolutions.com",
    "address": "101 Maple Ln",
    "zip": "13579",
    "state": "Florida",
    "country": "USA",
    "phone": "+1-555-444-5555"
  },
  {
    "id": 5,
    "name": "William Brown",
    "company": "Global Manufacturing",
    "username": "william_brown",
    "email": "william.brown@globalmfg.com",
    "address": "222 Pine St",
    "zip": "56789",
    "state": "California",
    "country": "USA",
    "phone": "+1-555-666-7777"
  },
  {
    "id": 6,
    "name": "Sophia Lee",
    "company": "Food Delights",
    "username": "sophia_lee",
    "email": "sophia.lee@fooddelights.com",
    "address": "333 Culinary Ave",
    "zip": "24680",
    "state": "New York",
    "country": "USA",
    "phone": "+1-555-888-9999"
  },
  {
    "id": 7,
    "name": "James Anderson",
    "company": "Financial Strategies",
    "username": "james_anderson",
    "email": "james.anderson@financialstrategies.com",
    "address": "444 Wealth St",
    "zip": "97531",
    "state": "Texas",
    "country": "USA",
    "phone": "+1-555-111-2222"
  },
  {
    "id": 8,
    "name": "Olivia Martin",
    "company": "EcoTech Solutions",
    "username": "olivia_martin",
    "email": "olivia.martin@ecotechsolutions.com",
    "address": "555 Green Rd",
    "zip": "54321",
    "state": "Florida",
    "country": "USA",
    "phone": "+1-555-333-4444"
  },
  {
    "id": 9,
    "name": "Robert Johnson",
    "company": "Fashion Trends Inc.",
    "username": "robert_johnson",
    "email": "robert.johnson@fashiontrends.com",
    "address": "666 Style Ave",
    "zip": "13579",
    "state": "California",
    "country": "USA",
    "phone": "+1-555-777-8888"
  },
  {
    "id": 10,
    "name": "Sophie Davis",
    "company": "Healthcare Solutions",
    "username": "sophie_davis",
    "email": "sophie.davis@healthcaresolutions.com",
    "address": "777 Wellness Rd",
    "zip": "24680",
    "state": "New York",
    "country": "USA",
    "phone": "+1-555-999-0000"
  },
  {
    "id": 11,
    "name": "Alexander Petrov",
    "company": "ABC Corporation",
    "username": "alexander_petrov",
    "email": "alexander.petrov@techware.com",
    "address": "567 Software St",
    "zip": "98765",
    "state": "Moscow",
    "country": "Italy",
    "phone": "+7-555-123-4567"
  },
  {
    "id": 12,
    "name": "Maria Ivanova",
    "company": "GazProm Corp",
    "username": "maria_ivanova",
    "email": "maria.ivanova@gazprom.com",
    "address": "789 Gaz Ave",
    "zip": "54321",
    "state": "St. Petersburg",
    "country": "Russia",
    "phone": "+7-555-987-6543"
  },
  {
    "id": 13,
    "name": "Raj Patel",
    "company": "TechSavvy Solutions",
    "username": "raj_patel",
    "email": "raj.patel@techsavvy.com",
    "address": "101 Tech Rd",
    "zip": "13579",
    "state": "Mumbai",
    "country": "India",
    "phone": "+91-555-222-3333"
  },
  {
    "id": 14,
    "name": "Priya Sharma",
    "company": "Taj Hospitality",
    "username": "priya_sharma",
    "email": "priya.sharma@tajhospitality.com",
    "address": "222 Taj Mahal St",
    "zip": "56789",
    "state": "Delhi",
    "country": "Italy",
    "phone": "+91-555-444-5555"
  },
  {
    "id": 15,
    "name": "Sebastian Schmidt",
    "company": "AutoTech GmbH",
    "username": "sebastian_schmidt",
    "email": "sebastian.schmidt@autotech.com",
    "address": "333 Auto Strasse",
    "zip": "24680",
    "state": "Berlin",
    "country": "Italy",
    "phone": "+49-555-888-9999"
  },
  {
    "id": 16,
    "name": "Isabella Rossi",
    "company": "ABC Corporation",
    "username": "isabella_rossi",
    "email": "isabella.rossi@fashionista.com",
    "address": "444 Via Moda",
    "zip": "97531",
    "state": "Milan",
    "country": "Italy",
    "phone": "+39-555-111-2222"
  },
  {
    "id": 17,
    "name": "Liam O'Connor",
    "company": "TechLink Ireland",
    "username": "liam_oconnor",
    "email": "liam.oconnor@techlink.com",
    "address": "555 Dublin Rd",
    "zip": "54321",
    "state": "Dublin",
    "country": "Ireland",
    "phone": "+353-555-333-4444"
  },
  {
    "id": 18,
    "name": "Emilia Nowak",
    "company": "Polish Innovations",
    "username": "emilia_nowak",
    "email": "emilia.nowak@polishinnovations.com",
    "address": "666 Warsaw St",
    "zip": "13579",
    "state": "Warsaw",
    "country": "Poland",
    "phone": "+48-555-777-8888"
  },
  {
    "id": 19,
    "name": "Miguel Fernández",
    "company": "EuroTech Solutions",
    "username": "miguel_fernandez",
    "email": "miguel.fernandez@eurotech.com",
    "address": "777 Madrid Ave",
    "zip": "24680",
    "state": "Madrid",
    "country": "Spain",
    "phone": "+34-555-999-0000"
  },
  {
    "id": 20,
    "name": "Ava Müller",
    "company": "Swiss Precision",
    "username": "ava_muller",
    "email": "ava.muller@swissprecision.com",
    "address": "888 Bern Strasse",
    "zip": "13579",
    "state": "Bern",
    "country": "Switzerland",
    "phone": "+41-555-111-2222"
  }
]