export const data = [
  { "id": 1, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 2, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 3, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 4, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 5, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 6, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 7, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 8, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 9, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 10, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 11, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 12, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 13, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 14, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 15, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 16, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 17, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 18, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 19, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 20, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 21, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 22, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 23, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 24, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 25, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 26, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 27, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 28, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 29, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 30, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },
  { "id": 31, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 32, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 33, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 34, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 35, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 36, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 37, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 38, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 39, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 40, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 41, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 42, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 43, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 44, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 45, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 46, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 47, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 48, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 49, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 50, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 51, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 52, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 53, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 54, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 55, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 56, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 57, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 58, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 59, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 60, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 61, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 62, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 63, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 64, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 65, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 66, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 67, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 68, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 69, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 70, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 71, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 72, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 73, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 74, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 75, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 76, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 77, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 78, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 79, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 80, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 81, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 82, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 83, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 84, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 85, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 86, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 87, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 88, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 89, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 90, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" },

  { "id": 91, "name": "Cotton Saree", "category": "Clothing", "price": 1299, "stock": 45, "supplier": "Sri Textiles", "status": "Available", "createdDate": "2025-01-10" },
  { "id": 92, "name": "Silk Saree", "category": "Clothing", "price": 5499, "stock": 12, "supplier": "Kanchipuram Weaves", "status": "Low Stock", "createdDate": "2025-01-12" },
  { "id": 93, "name": "Denim Shirt", "category": "Men Wear", "price": 899, "stock": 60, "supplier": "Urban Factory", "status": "Available", "createdDate": "2025-01-15" },
  { "id": 94, "name": "Bluetooth Headset", "category": "Electronics", "price": 1799, "stock": 20, "supplier": "TechZone", "status": "Available", "createdDate": "2025-01-18" },
  { "id": 95, "name": "LED Smart TV", "category": "Electronics", "price": 32999, "stock": 5, "supplier": "Samsung Store", "status": "Low Stock", "createdDate": "2025-01-20" },
  { "id": 96, "name": "Office Chair", "category": "Furniture", "price": 7499, "stock": 18, "supplier": "Feather Furnitures", "status": "Available", "createdDate": "2025-01-21" },
  { "id": 97, "name": "Study Table", "category": "Furniture", "price": 5999, "stock": 9, "supplier": "HomeCraft", "status": "Low Stock", "createdDate": "2025-01-22" },
  { "id": 98, "name": "Sports Shoes", "category": "Footwear", "price": 2999, "stock": 38, "supplier": "Nike Outlet", "status": "Available", "createdDate": "2025-01-23" },
  { "id": 99, "name": "Laptop Backpack", "category": "Bags", "price": 1299, "stock": 55, "supplier": "Skybags", "status": "Available", "createdDate": "2025-01-24" },
  { "id": 100, "name": "Water Bottle", "category": "Accessories", "price": 399, "stock": 150, "supplier": "Milton", "status": "Available", "createdDate": "2025-01-25" }
];

